#!/usr/bin/env python

import argparse


def parse_command_line():
    ''' parse command line options '''
    parser = argparse.ArgumentParser(
        description="Lint QE input file"
    )
    parser.add_argument(
        'file_in', metavar='file_in', type=str, help="file to read in and be linted"
    )
    parser.add_argument(
        '-o', '--output', action='store_true', help="if set then qe input file will be written to stdout"
    )

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_command_line()
    import pw2py as pw
    inp = pw.qeinp.from_file(args.file_in)
    if args.output:
        print(inp, end='')
    else:
        inp.write_file(args.file_in)
